using System;
using System.Collections.Generic;

namespace Api.Pricex.myDB
{
    public partial class StdSysConfig
    {
        public int Id { get; set; }
        public string RecordType { get; set; }
        public string Value001 { get; set; }
        public string Value002 { get; set; }
        public string Value003 { get; set; }
        public string Value004 { get; set; }
        public string Value005 { get; set; }
        public string Value006 { get; set; }
        public string Value007 { get; set; }
        public string Value008 { get; set; }
        public string Value009 { get; set; }
        public string Value010 { get; set; }
        public string Value011 { get; set; }
        public string Value012 { get; set; }
        public string Value013 { get; set; }
        public string Value014 { get; set; }
        public string Value015 { get; set; }
        public string Value016 { get; set; }
        public string Value017 { get; set; }
        public string Value018 { get; set; }
        public string Value019 { get; set; }
        public string Value020 { get; set; }
        public string Value021 { get; set; }
        public string Value022 { get; set; }
        public string Value023 { get; set; }
        public string Value024 { get; set; }
        public string Value025 { get; set; }
        public string Value026 { get; set; }
        public string Value027 { get; set; }
        public string Value028 { get; set; }
        public string Value029 { get; set; }
        public string Value030 { get; set; }
        public string Value031 { get; set; }
        public string Value032 { get; set; }
        public string Value033 { get; set; }
        public string Value034 { get; set; }
        public string Value035 { get; set; }
        public string Value036 { get; set; }
        public string Value037 { get; set; }
        public string Value038 { get; set; }
        public string Value039 { get; set; }
        public string Value040 { get; set; }
        public string Value041 { get; set; }
        public string Value042 { get; set; }
        public string Value043 { get; set; }
        public string Value044 { get; set; }
        public string Value045 { get; set; }
        public string Value046 { get; set; }
        public string Value047 { get; set; }
        public string Value048 { get; set; }
        public string Value049 { get; set; }
        public string Value050 { get; set; }
        public string Value051 { get; set; }
        public string Value052 { get; set; }
        public string Value053 { get; set; }
        public string Value054 { get; set; }
        public string Value055 { get; set; }
        public string Value056 { get; set; }
        public string Value057 { get; set; }
        public string Value058 { get; set; }
        public string Value059 { get; set; }
        public string Value060 { get; set; }
        public string Value061 { get; set; }
        public string Value062 { get; set; }
        public string Value063 { get; set; }
        public string Value064 { get; set; }
        public string Value065 { get; set; }
        public string Value066 { get; set; }
        public string Value067 { get; set; }
        public string Value068 { get; set; }
        public string Value069 { get; set; }
        public string Value070 { get; set; }
        public string Value071 { get; set; }
        public string Value072 { get; set; }
        public string Value073 { get; set; }
        public string Value074 { get; set; }
        public string Value075 { get; set; }
        public string Value076 { get; set; }
        public string Value077 { get; set; }
        public string Value078 { get; set; }
        public string Value079 { get; set; }
        public string Value080 { get; set; }
        public string Value081 { get; set; }
        public string Value082 { get; set; }
        public string Value083 { get; set; }
        public string Value084 { get; set; }
        public string Value085 { get; set; }
        public string Value086 { get; set; }
        public string Value087 { get; set; }
        public string Value088 { get; set; }
        public string Value089 { get; set; }
        public string Value090 { get; set; }
        public string Value091 { get; set; }
        public string Value092 { get; set; }
        public string Value093 { get; set; }
        public string Value094 { get; set; }
        public string Value095 { get; set; }
        public string Value096 { get; set; }
        public string Value097 { get; set; }
        public string Value098 { get; set; }
        public string Value099 { get; set; }
        public string Value100 { get; set; }
        public string Value101 { get; set; }
        public string Value102 { get; set; }
        public string Value103 { get; set; }
        public string Value104 { get; set; }
        public string Value105 { get; set; }
        public string Value106 { get; set; }
        public string Value107 { get; set; }
        public string Value108 { get; set; }
        public string Value109 { get; set; }
        public string Value110 { get; set; }
        public string Value111 { get; set; }
        public string Value112 { get; set; }
        public string Value113 { get; set; }
        public string Value114 { get; set; }
        public string Value115 { get; set; }
        public string Value116 { get; set; }
        public string Value117 { get; set; }
        public string Value118 { get; set; }
        public string Value119 { get; set; }
        public string Value120 { get; set; }
        public string Value121 { get; set; }
        public string Value122 { get; set; }
        public string Value123 { get; set; }
        public string Value124 { get; set; }
        public string Value125 { get; set; }
        public string Value126 { get; set; }
        public string Value127 { get; set; }
        public string Value128 { get; set; }
        public string Value129 { get; set; }
        public string Value130 { get; set; }
        public string Value131 { get; set; }
        public string Value132 { get; set; }
        public string Value133 { get; set; }
        public string Value134 { get; set; }
        public string Value135 { get; set; }
        public string Value136 { get; set; }
        public string Value137 { get; set; }
        public string Value138 { get; set; }
        public string Value139 { get; set; }
        public string Value140 { get; set; }
        public string Value141 { get; set; }
        public string Value142 { get; set; }
        public string Value143 { get; set; }
        public string Value144 { get; set; }
        public string Value145 { get; set; }
        public string Value146 { get; set; }
        public string Value147 { get; set; }
        public string Value148 { get; set; }
        public string Value149 { get; set; }
        public string Value150 { get; set; }
        public string Value151 { get; set; }
        public string Value152 { get; set; }
        public string Value153 { get; set; }
        public string Value154 { get; set; }
        public string Value155 { get; set; }
        public string Value156 { get; set; }
        public string Value157 { get; set; }
        public string Value158 { get; set; }
        public string Value159 { get; set; }
        public string Value160 { get; set; }
        public string Value161 { get; set; }
        public string Value162 { get; set; }
        public string Value163 { get; set; }
        public string Value164 { get; set; }
        public string Value165 { get; set; }
        public string Value166 { get; set; }
        public string Value167 { get; set; }
        public string Value168 { get; set; }
        public string Value169 { get; set; }
        public string Value170 { get; set; }
        public string Value171 { get; set; }
        public string Value172 { get; set; }
        public string Value173 { get; set; }
        public string Value174 { get; set; }
        public string Value175 { get; set; }
        public string Value176 { get; set; }
        public string Value177 { get; set; }
        public string Value178 { get; set; }
        public string Value179 { get; set; }
        public string Value180 { get; set; }
        public string Value181 { get; set; }
        public string Value182 { get; set; }
        public string Value183 { get; set; }
        public string Value184 { get; set; }
        public string Value185 { get; set; }
        public string Value186 { get; set; }
        public string Value187 { get; set; }
        public string Value188 { get; set; }
        public string Value189 { get; set; }
        public string Value190 { get; set; }
        public string Value191 { get; set; }
        public string Value192 { get; set; }
        public string Value193 { get; set; }
        public string Value194 { get; set; }
        public string Value195 { get; set; }
        public string Value196 { get; set; }
        public string Value197 { get; set; }
        public string Value198 { get; set; }
        public string Value199 { get; set; }
        public string Value200 { get; set; }
        public string Value201 { get; set; }
        public string Value202 { get; set; }
        public string Value203 { get; set; }
        public string Value204 { get; set; }
        public string Value205 { get; set; }
        public string Value206 { get; set; }
        public string Value207 { get; set; }
        public string Value208 { get; set; }
        public string Value209 { get; set; }
        public string Value210 { get; set; }
        public string Value211 { get; set; }
        public string Value212 { get; set; }
        public string Value213 { get; set; }
        public string Value214 { get; set; }
        public string Value215 { get; set; }
        public string Value216 { get; set; }
        public string Value217 { get; set; }
        public string Value218 { get; set; }
        public string Value219 { get; set; }
        public string Value220 { get; set; }
    }
}
